name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate bash script
        run: bash -n scripts/system-monitor.sh

      - name: Install shellCheck
        run: sudo apt-get update && sudo apt-get install shellcheck

      - name: Run shellCheck
        run: shellcheck ./scripts/system-monitor.sh

      - name: Build docker image
        run: docker build -t linux-system-monitor .

      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-action/amazon-ecr-login@v2

      - name: Tag Docker Image
        run: | 
          docker tag linux-system-monitor:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/linux-system-monitor:latest

      - name: Push Docker Image 
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/linux-system-monitor:latest
